[package]
name = "rust-esetupdater"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
indexmap = { version = "2.9.0", features = ["serde"] }
log = "0.4.27"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_ini = "0.2.0"
serde_json = "1.0.140"
simplelog = "0.12.2"
toml = "0.8.22"
