### Example of configuration file

[local]
root_dir = "./web_test"               # path to root directory where updates are stored. can be absolute or relative. Example: "/var/www/public_html"  
sub_dir = "eset_upd"                  # additional subdirectory. Example: "eset_upd", resulting path will be "/var/www/public_html/eset_upd"
update_ver_new = "/dll/update.ver"    # path to new update file. no need to change. definitely should start with "dll/" to make it work
update_ver_old = "/dll/.update.ver"   # path to old update file. same as above

[remote]
host = "http://example.com"           # host address where to download updates from
host_path = "eset_upd"                # additional suffix is host uses non-standart directory structure. resulting path will be "http://example.com/eset_upd"
user = "my_user"                      # username for basic Auth if used
password = "my_password"              # password for basic Auth if used

                                      # user_agent string necessary for downloading updates 
user_agent = "EEA Update (Windows; U; 64bit; BPC 11.0.2044.0; OS: 10.0.26100 SP 0.0 NT; HWF: 921b979f-686d-4fa2-bebb-3ffe2ab877da; PLOC ru_ru; PCODE 107.0.0; PAR -1; ATH -1; DC 0; PLID 3AC-9SP-9D9; SEAT 154b3474; RET 2107)"

[settings]
platforms = ["x64"]                   # list of desired platforms. Full list: ["x64", "x86", "arm"] . This will download updates for all platforms.
